logging:
  level:
    com:
      cts: DEBUG
    org:
      springframework:
        web: ERROR
    s7:
      Application: WARN
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-service
  datasource:
    driverClassName: org.h2.Driver
    password: 123
    url: jdbc:h2:mem:auth
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  sql:
    init:
      mode: always
